# --------------------------------------
# view
#
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
on_event = ['VimEnter']
hook_source = '''
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_guide_size = 1
let g:indent_guides_start_level = 2
'''

# --------------------------------------
# edit
#
[[plugins]]
repo = 'tyru/caw.vim'
on_event = ['VimEnter']

[[plugins]]
repo = 'machakann/vim-sandwich'
on_event = ['VimEnter']

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_event = ['VimEnter']

# --------------------------------------
# Python
#
[[plugins]]
repo = 'goerz/jupytext.vim'
on_event = ['VimEnter']
hook_source = '''
let g:jupytext_enable = 1
let g:jupytext_fmt = 'py:percent'
let g:jupytext_filetype_map = {'py': 'python'}
'''
