[[plugins]]
# https://note.com/dd_techblog/n/n97f2b6ca09d8
repo = 'Shougo/ddc.vim'
if = "has('nvim')"
on_event = ['InsertEnter']
depends = ['denops.vim']
hook_source = '''
call ddc#custom#patch_global('sources', [
  \ 'around',
  \ 'vim-lsp'
  \ ])
call ddc#custom#patch_global('sourceOptions', {
  \ '_': {
  \   'matchers': ['matcher_head'],
  \   'sorters': ['sorter_rank'],
  \   'converters': ['converter_remove_overlap'],
  \ },
  \ 'around': {
  \   'mark': 'Around'
  \ },
  \ 'vim-lsp': {
  \   'mark': 'LSP',
  \   'matchers': ['matcher_head'],
  \   'forceCompletionPattern': '\.|:|->|"\w+/*'
  \ }
  \})
call ddc#enable()
'''

[[plugins]]
repo = 'Shougo/ddc-around'
if = "has('nvim')"
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
if = "has('nvim')"
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
if = "has('nvim')"
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
if = "has('nvim')"
on_source = ['ddc.vim']
