# --------------------------------------
# Shougo
#
[[plugins]]
repo = 'Shougo/dein.vim'

# --------------------------------------
# Deno
#
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-denops/denops-helloworld.vim'

# --------------------------------------
# LSP
#
[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
# https://zenn.dev/mattn/articles/b83f9d94202914
repo = 'mattn/vim-lsp-settings'

# --------------------------------------
# view
#
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_guide_size = 1
let g:indent_guides_start_level = 2
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
let g:winresizer_start_key = "\<C-w>\<C-w>"
'''

# --------------------------------------
# edit
#
[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'machakann/vim-sandwich'

# --------------------------------------
# colorscheme
#
[[plugins]]
repo = 'tomasiser/vim-code-dark'
hook_source = '''
set t_Co=256
set t_ut=
colorscheme codedark
'''

# --------------------------------------
# statusline
#
[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['syntastic']
hook_source = '''
set laststatus=2
set noshowmode
if !has('gui_running')
  set t_Co=256
endif

let g:lightline = {
\ 'colorscheme': 'default',
\ 'component': {
\   'mylineinfo': '%3l/%L, %-2c'
\ },
\ 'active': {
\   'left': [
\     ['mode', 'paste'],
\     ['filename', 'readonly', 'modified'],
\     ['mypath']
\   ],
\   'right': [
\     ['mylineinfo'],
\     ['fileformat', 'fileencoding', 'filetype']
\   ]
\ },
\ 'inactive': {
\   'left': [
\     ['filename']
\   ],
\   'right': [
\     []
\   ]
\ },
\ 'tabline': {
\   'left': [
\     ['tabs']
\   ],
\   'right': [
\     ['mycwdname']
\   ]
\ },
\ 'separator': {
\   'left': '',
\   'right': ''
\ },
\ 'component_function': {
\   'mycwdname': 'LLGetCwdName',
\   'mypath': 'LLGetPath'
\ }
\}

function! LLGetCwdName()
  return fnamemodify(getcwd(), ':t')
endfunction
function! LLGetPath()
  return substitute(fnamemodify(@%, ':p:h'), '\\', '\/', 'g')
endfunction
'''

# --------------------------------------
# Python
#
[[plugins]]
repo = 'goerz/jupytext.vim'
hook_add = '''
let g:jupytext_enable = 1
let g:jupytext_fmt = 'py:percent'
let g:jupytext_filetype_map = {'py': 'python'}
'''
