# --------------------------------------
# Deno
#
[[plugins]]
repo = 'vim-denops/denops.vim'

# --------------------------------------
# Python
#
[[plugins]]
repo = 'goerz/jupytext.vim'
hook_add = '''
let g:jupytext_enable = 1
let g:jupytext_fmt = 'py:percent'
let g:jupytext_filetype_map = {'py': 'python'}
'''
