# --------------------------------------
# view
#
[[plugins]]
repo = 'simeji/winresizer'
on_event = ['VimEnter']
hook_source = '''
let g:winresizer_start_key = "\<C-w>\<C-w>"
let g:winresizer_horiz_resize = 1
let g:winresizer_vert_resize = 5
'''

# --------------------------------------
# edit
#
[[plugins]]
repo = 'tyru/caw.vim'
on_event = ['VimEnter']

[[plugins]]
repo = 'machakann/vim-sandwich'
on_event = ['VimEnter']

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_event = ['VimEnter']
hook_source = '''
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)
'''

# --------------------------------------
# colorscheme
#
[[plugins]]
repo = 'sainnhe/gruvbox-material'
on_event = ['VimEnter']
hook_post_source = '''
" Important!!
if has('termguicolors')
  set termguicolors
endif

" For dark version.
set background=dark

" Set contrast.
" This configuration option should be placed before `colorscheme gruvbox-material`.
" Available values: 'hard', 'medium'(default), 'soft'
let g:gruvbox_material_background = 'medium'

" For better performance
let g:gruvbox_material_better_performance = 1
let g:gruvbox_material_disable_italic_comment = 1
colorscheme gruvbox-material
'''
