# --------------------------------------
# Shougoware
#
[[plugins]]
repo = 'Shougo/dein.vim'

# --------------------------------------
# Deno
#
[[plugins]]
repo = 'vim-denops/denops.vim'

# --------------------------------------
# view
#
[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_guide_size = 1
let g:indent_guides_start_level = 2
'''

# --------------------------------------
# edit
#
[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'vim-syntastic/syntastic'
hook_add = '''
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_loc_list_height = 3
let g:syntastic_mode_map = {'mode': 'passive'}
let g:syntastic_python_checkers = ['flake8']
'''

# --------------------------------------
# colorscheme
#
[[plugins]]
repo = 'tomasiser/vim-code-dark'
hook_add = '''
set t_Co=256
set t_ut=
colorscheme codedark
'''

# --------------------------------------
# statusline
#
[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['syntastic']
hook_add = '''
set laststatus=2
set noshowmode
if !has('gui_running')
  set t_Co=256
endif

let g:lightline = {
\ 'colorscheme': 'default',
\ 'component': {
\   'mylineinfo': '%3l/%L, %-2c'
\ },
\ 'active': {
\   'left': [
\     ['mode', 'paste'],
\     ['filename', 'readonly', 'modified']
\   ],
\   'right': [
\     ['syntastic', 'mylineinfo'],
\     ['fileformat', 'fileencoding', 'filetype']
\   ]
\ },
\ 'inactive': {
\   'left': [
\     ['filename']
\   ],
\   'right': [
\     []
\   ]
\ },
\ 'tabline': {
\   'left': [
\     ['tabs']
\   ],
\   'right': [
\     ['mydirname']
\   ]
\ },
\ 'separator': {
\   'left': '',
\   'right': ''
\ },
\ 'component_function': {
\   'mydirpath': 'LLGetDirPath',
\   'mydirname': 'LLGetDirName'
\ },
\ 'component_expand':{
\   'syntastic': 'SyntasticStatuslineFlag'
\ },
\ 'component_type': {
\   'syntastic': 'error'
\ }
\}

function! LLGetDirName()
  return fnamemodify(getcwd(), ':t')
endfunction

function! LLGetDirPath()
  return fnamemodify(getcwd(), ':p:h')
endfunction

augroup MyAutoSyntastic
  autocmd!
  autocmd BufEnter,BufWritePost * call LLSyntastic()
augroup END

function! LLSyntastic()
  SyntasticCheck
  call lightline#update()
endfunction
'''

# --------------------------------------
# Python
#
[[plugins]]
repo = 'goerz/jupytext.vim'
hook_add = '''
let g:jupytext_enable = 1
let g:jupytext_fmt = 'py:percent'
let g:jupytext_filetype_map = {'py': 'python'}
'''
