# --------------------------------------
# terminal
#
[[plugins]]
repo = 'kassio/neoterm'
on_event = ['VimEnter']
hook_source = '''
let g:neoterm_autoscroll = 1
let g:neoterm_default_mod = 'botright'
let g:neoterm_eof = "\r\n"
let g:neoterm_size = 10

nnoremap <silent> <Plug>(my-terminal)oh   <Cmd>call <SID>split(v:count)<CR>
nnoremap <silent> <Plug>(my-terminal)ov   <Cmd>call <SID>vsplit()<CR>

function! s:split(size) abort
  let l:tmpmod = g:neoterm_default_mod
  let l:tmpsize = g:neoterm_size
  if a:size > 0
   let l:asize = a:size
  else
    let l:asize = l:tmpsize
  endif
  let g:neoterm_default_mod = 'botright'
  let g:neoterm_size = l:asize
  Tnew
  let g:neoterm_default_mod = l:tmpmod
  let g:neoterm_size = l:tmpsize
endfunction

function! s:vsplit() abort
  let l:tmpmod = g:neoterm_default_mod
  let l:tmpsize = g:neoterm_size
  let g:neoterm_default_mod = 'vertical'
  let g:neoterm_size = ''
  Tnew
  let g:neoterm_default_mod = l:tmpmod
  let g:neoterm_size = l:tmpsize
endfunction

nnoremap <silent> <Plug>(my-terminal)emm  <Cmd>execute 'T' "mmdc -i" fnamemodify(@%, ':t') "-o" fnamemodify(@%, ':t:r') . ".svg && mmdc -i" fnamemodify(@%, ':t') "-o" fnamemodify(@%, ':t:r') . ".png"<CR>
nnoremap <silent> <Plug>(my-terminal)epu  <Cmd>execute 'T' "java -jar" g:my_plantuml_path fnamemodify(@%, ':p') "-charset UTF-8 -svg && java -jar" g:my_plantuml_path fnamemodify(@%, ':p') "-charset UTF-8 -png"<CR>

nnoremap <silent> <Plug>(my-terminal)sjp  <Cmd>execute 'TREPLSetTerm' split(@%, '-')[-1]<CR>
nnoremap <silent> <Plug>(my-terminal)spy  <Nop>
nnoremap <silent> <Plug>(my-terminal)sr   <Nop>
nnoremap <silent> <Plug>(my-terminal)ssq  <Cmd>execute v:count.'T' "pg_ctl start && psql -U postgres -d recipe"<CR>

nnoremap <silent> <Plug>(my-terminal)rjp  <Cmd>call <SID>send_cell()<CR>
nnoremap <silent> <Plug>(my-terminal)rpy  <Cmd>execute v:count.'T' "python" @a<CR>
nnoremap <silent> <Plug>(my-terminal)rr   <Cmd>execute v:count.'T' "rscript --encoding=utf-8" @a<CR>
nnoremap <silent> <Plug>(my-terminal)rsq  <Cmd>execute v:count.'T' "\i" @a<CR>

function! s:send_cell() abort
  let l:cell_delimiter = '# %%'
  let l:line_ini = search(l:cell_delimiter, 'bcnW')
  let l:line_end = search(l:cell_delimiter, 'nW')

  let l:line_ini = l:line_ini ? l:line_ini + 1 : 1
  let l:line_end = l:line_end ? l:line_end - 1 : line("$")

  if line_ini <= line_end
    " execute line_ini .','. line_end 'call TREPLSendSelection()'
    call neoterm#repl#line(line_ini, line_end)
  else
    echo 'sending cell failed'
  endif
endfunction
'''

# --------------------------------------
# highlight
#
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = ['VimEnter']
hook_post_update = 'TSUpdate'
hook_source = '''
lua <<EOF
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
    disable = {},
  },
  indent = {
    enable = true,
    disable = {},
  },
  ensure_installed = {
    "bash",
    "css",
    "json",
    "markdown",
    "python",
    "r",
    "toml",
    "vim",
  },
  additional_vim_regex_highlighting = false,
}
EOF
'''

# --------------------------------------
# Python
#
[[plugins]]
repo = 'goerz/jupytext.vim'
on_event = ['VimEnter']
hook_source = '''
let g:jupytext_enable = 1
let g:jupytext_fmt = 'py:percent'
let g:jupytext_filetype_map = {'py': 'python'}
'''
