[[plugins]]
https://github.com/neoclide/coc.nvim/wiki/Language-servers
repo = 'neoclide/coc.nvim'
if = "has('nvim')"
hook_post_update = '''
call coc#util#install()
CocInstall coc-json
CocInstall coc-markdownlint
CocInstall coc-pyright
'''

[[plugins]]
repo = 'vim-syntastic/syntastic'
if = "has('nvim')"
hook_add = '''
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_loc_list_height = 3
let g:syntastic_mode_map = {'mode': 'passive'}
let g:syntastic_python_checkers = ['flake8']
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['syntastic']
hook_source = '''
let g:lightline = {
\ 'colorscheme': 'default',
\ 'active': {
\   'right': [
\     ['syntastic']
\   ]
\ },
\ 'component_expand':{
\   'coc': 'coc#status',
\   'syntastic': 'SyntasticStatuslineFlag'
\ },
\ 'component_type': {
\   'coc': 'error',
\   'syntastic': 'error'
\ }
\}
augroup LLAutoUpdate
  autocmd!
  autocmd BufWritePost * call LLSyntastic()
augroup END
nnoremap <silent> <Plug>(my-edit)y :call LLSyntastic()<CR>
function! LLSyntastic()
  SyntasticCheck
  call lightline#update()
endfunction
'''
