# --------------------------------------
# highlight
#
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = ['VimEnter']
hook_post_update = 'TSUpdate'
hook_source = '''
lua <<EOF
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
    disable = {},
  },
  indent = {
    enable = true,
    disable = {},
  },
  ensure_installed = {
    "bash",
    "css",
    "json",
    "markdown",
    "python",
    "r",
    "toml",
    "vim",
  },
  additional_vim_regex_highlighting = false,
}
EOF
'''

# --------------------------------------
# Python
#
[[plugins]]
repo = 'goerz/jupytext.vim'
on_event = ['VimEnter']
hook_source = '''
let g:jupytext_enable = 1
let g:jupytext_fmt = 'py:percent'
let g:jupytext_filetype_map = {'py': 'python'}
'''
