[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Lokaltog/vim-powerline'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'simeji/winresizer'

# --------------------------------------
# Git
#
#[[plugins]]
#repo = 'airblade/vim-gitgutter'

#[[plugins]]
#repo = 'tpope/vim-fugitive'

# --------------------------------------
# Syntax
#
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = 'plantuml'

[[plugins]]
repo = 'mechatroner/rainbow_csv'
on_ft = 'csv'

# --------------------------------------
# Markdown
#
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_ft = 'markdown'

# --------------------------------------
# Python
#
[[plugins]]
repo = 'goerz/jupytext.vim'
on_ft = 'python'
