[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'Lokaltog/vim-powerline'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'simeji/winresizer'

# --------------------------------------
# Syntax
#
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = 'plantuml'

[[plugins]]
repo = 'mechatroner/rainbow_csv'
on_ft = 'csv'

# --------------------------------------
# Markdown
#
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_ft = 'markdown'

# --------------------------------------
# Python
#
[[plugins]]
repo = 'goerz/jupytext.vim'
on_ft = 'python'
