[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'

# --------------------------------------
# Theme
#
[[plugins]]
repo = 'itchyny/lightline.vim'

# --------------------------------------
# Syntax
#
[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = 'plantuml'

[[plugins]]
repo = 'mechatroner/rainbow_csv'
on_ft = 'csv'

# --------------------------------------
# Markdown
#
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'godlygeek/tabular'
on_ft = 'markdown'

# --------------------------------------
# Python
#
# [[plugins]]
# repo = 'goerz/jupytext.vim'
# on_ft = 'python'
