# --------------------------------------
# Shougo
#
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# --------------------------------------
# Edit
#
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
# FixWhitespace
repo = 'bronson/vim-trailing-whitespace'

# --------------------------------------
# Theme
#
[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'itchyny/lightline.vim'

# --------------------------------------
# Syntax
#
[[plugins]]
repo = 'mechatroner/rainbow_csv'
on_ft = 'csv'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = 'plantuml'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# --------------------------------------
# Markdown
#
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'

[[plugins]]
# required by 'plasticboy/vim-markdown'
repo = 'godlygeek/tabular'
on_ft = 'markdown'
