[[plugins]]
repo = 'Shougo/dein.vim'

#[[plugins]]
#repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

# --------------------------------------
# Markdown
#
[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

# --------------------------------------
# Syntax
#
[[plugins]]
repo = 'aklt/plantuml-syntax'

[[plugins]]
repo = 'mechatroner/rainbow_csv'

# --------------------------------------
# Git
#
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'
