# --------------------------------------
# Python
#
[[plugins]]
repo='goerz/jupytext.vim'
on_ft=['python']
hook_source='''
let g:jupytext_enable = 1
let g:jupytext_fmt = 'py:percent'
let g:jupytext_filetype_map = {'py': 'python'}
nnoremap <silent> <Space>js :Silent jupytext --sync .\*.ipynb<CR>
'''

[[plugins]]
repo='jpalardy/vim-slime'
on_ft=['python', 'r', 'sql']
hook_source='''
let g:slime_target = "neovim"
let g:slime_cell_delimiter = "#\ %%"

command! -nargs=0 MyIPython call MyIPython()
function! MyIPython() abort
  execute 'vsplit | wincmd l | terminal'
  call feedkeys("i" . "activate.bat" . "\<CR>\<Esc>")
  call feedkeys("i" . "ipython" . "\<CR>\<Esc>")
  call feedkeys("\<C-W>h")
endfunction
'''

[[plugins]]
repo='hanschen/vim-ipython-cell'
on_ft=['python', 'sql']
hook_source='''
nnoremap <C-M> :call ExecuteCell()<CR>
function! ExecuteCell() abort
  execute 'IPythonCellExecuteCell'
  execute 'wincmd l'
  call feedkeys("i" . "\<CR>\<Esc>")
  call feedkeys("\<C-W>h")
endfunction
'''
