# --------------------------------------
# Shougo
#
[[plugins]]
repo = 'Shougo/dein.vim'

# --------------------------------------
# Edit
#
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_source = '''
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_guide_size = 1
let g:indent_guides_start_level = 2
'''

[[plugins]]
repo = 'tyru/caw.vim'

# --------------------------------------
# Status Line
#
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_source = '''
let g:lightline = {
\   'colorscheme': 'ayu_dark',
\   'component': {
\       'mylineinfo': '%3l/%L, %-2c',
\       'dir': '%{getcwd()}'
\   },
\   'active': {
\       'left': [
\           ['mode', 'paste'],
\           ['readonly', 'dir', 'filename', 'modified']
\       ],
\       'right': [
\           ['mylineinfo'],
\           ['fileformat', 'fileencoding', 'filetype']
\       ]
\   },
\   'inactive': {
\       'left': [
\           ['dir', 'filename']
\       ],
\       'right': [
\           ['mylineinfo']
\       ]
\   },
\   'separator': {
\       'left': '|',
\       'right': '|'
\   },
\}
'''
