# --------------------------------------
# Shougo
#
[[plugins]]
repo='Shougo/dein.vim'

# --------------------------------------
# View
#
[[plugins]]
repo='simeji/winresizer'
hook_add='''
let g:winresizer_start_key='<C-w><C-w>'
'''

# --------------------------------------
# Edit
#
[[plugins]]
repo='nathanaelkane/vim-indent-guides'
hook_source='''
let g:indent_guides_enable_on_vim_startup=1
let g:indent_guides_guide_size=1
let g:indent_guides_start_level=2
'''

[[plugins]]
repo='tyru/caw.vim'

# --------------------------------------
# Color Scheme
#
[[plugins]]
repo='tomasiser/vim-code-dark'
hook_source='''
set t_Co=256
set t_ut=
'''

# --------------------------------------
# Status Line
#
[[plugins]]
repo='itchyny/lightline.vim'
hook_source='''
let g:lightline={
\   'component': {
\       'mylineinfo': '%3l/%L, %-2c',
\       'dir': '%{getcwd()}'
\   },
\   'active': {
\       'left': [
\           ['mode', 'paste'],
\           ['readonly', 'dir', 'filename', 'modified']
\       ],
\       'right': [
\           ['mylineinfo'],
\           ['fileformat', 'fileencoding', 'filetype']
\       ]
\   },
\   'inactive': {
\       'left': [
\           ['dir', 'filename']
\       ],
\       'right': [
\           ['mylineinfo']
\       ]
\   },
\   'separator': {
\       'left': '|',
\       'right': '|'
\   },
\}
'''
