# --------------------------------------
# Python
#
[[plugins]]
repo='goerz/jupytext.vim'
on_ft=['python']
hook_source='''
let g:jupytext_enable = 1
let g:jupytext_fmt = 'py:percent'
let g:jupytext_filetype_map = {'py': 'python'}
nnoremap <silent> <Space>js :Silent jupytext --sync .\*.ipynb<CR>
'''

[[plugins]]
repo='jpalardy/vim-slime'
on_ft=['python']
hook_source='''
if has('nvim')
  let g:slime_target = "neovim"
else
  let g:slime_target = "vimterminal"
endif
let g:slime_python_ipython = 1
let g:slime_cell_delimiter = "# %%"
'''

[[plugins]]
repo='hanschen/vim-ipython-cell'
on_ft=['python']
hook_source='''
nnoremap <silent> <Space>ie :call ExecuteCell()<CR>
nnoremap <silent> <Space>is :call StartIPython()<CR>

function! ExecuteCell() abort
  execute 'IPythonCellExecuteCell'
  execute 'wincmd l'
  call feedkeys("i" . "\<CR>\<Esc>")
  call feedkeys("\<C-W>h")
endfunction

function! StartIPython() abort
  execute 'vsplit | wincmd l | terminal'
  call feedkeys("i" . "activate" . "\<CR>\<Esc>")
  call feedkeys("i" . "ipython" . "\<CR>\<Esc>")
  call feedkeys("\<C-W>h")
endfunction
'''
