# --------------------------------------
# Shougo
#
[[plugins]]
repo='Shougo/neosnippet.vim'
on_ft=['markdown']
hook_source='''
let g:neosnippet#snippets_directory='~/.vim/snippets'
imap <C-k> <Plug>(neosnippet_expand_or_jump)
smap <C-k> <Plug>(neosnippet_expand_or_jump)
xmap <C-k> <Plug>(neosnippet_expand_target)
'''

[[plugins]]
repo='Shougo/neosnippet-snippets'
on_source=['neosnippet.vim']

# --------------------------------------
# Markdown
#
[[plugins]]
repo='plasticboy/vim-markdown'
on_ft=['markdown']
hook_source='''
let g:tex_conceal=""
let g:vim_markdown_conceal=0
let g:vim_markdown_conceal_code_blocks=0
let g:vim_markdown_folding_disabled=1
let g:vim_markdown_math=1
let g:vim_markdown_no_default_key_mappings=1
nnoremap <silent> <Space>ft :TableFormat<CR>
'''

[[plugins]]
# required by 'plasticboy/vim-markdown'
repo='godlygeek/tabular'
on_source=['vim-markdown']

# --------------------------------------
# Python
#
[[plugins]]
repo='goerz/jupytext.vim'
on_ft=['python']
hook_source='''
let g:jupytext_enable = 1
let g:jupytext_fmt = 'py:percent'
let g:jupytext_filetype_map = {'py': 'python'}
nnoremap <silent> <Space>js :Silent jupytext --sync .\*.ipynb<CR>
'''

[[plugins]]
repo='jpalardy/vim-slime'
on_ft=['python']
hook_source='''
if has('nvim')
  let g:slime_target = "neovim"
else
  let g:slime_target = "vimterminal"
endif
let g:slime_python_ipython = 1
let g:slime_cell_delimiter = "# %%"
'''

[[plugins]]
repo='hanschen/vim-ipython-cell'
on_ft=['python']
hook_source='''
nnoremap <C-M> :IPythonCellExecuteCell<CR>
'''
